database:
  build: ./database
  container_name: testify-database
  ports:
    - "5432:5432"

server:
  build: ./server
  container_name: testify-server
  links:
    - database:database
  ports:
    - "8000:8000"
  environment:
    - NODE_ENV=development

client:
  build: ./client
  container_name: testify-client
  links:
    - server:server
  ports:
    - "8080:80"
  volumes:
    - "./client/app:/app"
  environment:
    - ENVIRONMENT=development
